global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@freemarket.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
  routes:
  - match:
      severity: critical
    receiver: 'email'
  - match:
      severity: warning
    receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'admin@freemarket.com'
    send_resolved: true

- name: 'telegram'
  webhook_configs:
  - url: 'http://telegram-bot:8080/alert'
    send_resolved: true
